# Generated by Django 4.2 on 2023-04-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_productmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
