# Generated by Django 4.2 on 2023-05-07 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
