# Generated by Django 4.2.1 on 2023-05-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=19),
        ),
    ]
